sudo: required
dist: trusty
language: node_js
node_js:
  - 6

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - if [[ "$MUTATE" == "true" ]]; then
      npm install -g stryker-cli;
    fi

script: 
  - ./node_modules/.bin/run-tests

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=firefox BVER=stable
    - UNIT_CMD='npm run lint'
    - BROWSER=chrome  BVER=stable UNIT_CMD='stryker run' MUTATE='true'
  global:
    - TRAVIS=true
    - UNIT_CMD='npm run unit'

matrix:
  fast_finish: true

notifications:
  email:
    - manik@tokbox.com
